// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          phone: string | null
          role: 'customer' | 'seller' | 'admin'
          stripe_customer_id: string | null
          email_verified: boolean
          is_active: boolean
          last_login_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          role?: 'customer' | 'seller' | 'admin'
          stripe_customer_id?: string | null
          email_verified?: boolean
          is_active?: boolean
          last_login_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          role?: 'customer' | 'seller' | 'admin'
          stripe_customer_id?: string | null
          email_verified?: boolean
          is_active?: boolean
          last_login_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      seller_profiles: {
        Row: {
          id: string
          user_id: string
          store_name: string
          store_slug: string
          store_description: string | null
          store_logo_url: string | null
          store_banner_url: string | null
          business_email: string | null
          business_phone: string | null
          business_address: Json | null
          stripe_account_id: string | null
          stripe_onboarding_complete: boolean
          commission_rate: number
          status: 'pending' | 'approved' | 'suspended' | 'rejected'
          rating_average: number
          rating_count: number
          total_sales: number
          total_revenue: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          store_name: string
          store_slug: string
          store_description?: string | null
          store_logo_url?: string | null
          store_banner_url?: string | null
          business_email?: string | null
          business_phone?: string | null
          business_address?: Json | null
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          commission_rate?: number
          status?: 'pending' | 'approved' | 'suspended' | 'rejected'
          rating_average?: number
          rating_count?: number
          total_sales?: number
          total_revenue?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          store_name?: string
          store_slug?: string
          store_description?: string | null
          store_logo_url?: string | null
          store_banner_url?: string | null
          business_email?: string | null
          business_phone?: string | null
          business_address?: Json | null
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          commission_rate?: number
          status?: 'pending' | 'approved' | 'suspended' | 'rejected'
          rating_average?: number
          rating_count?: number
          total_sales?: number
          total_revenue?: number
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          parent_id: string | null
          name: string
          slug: string
          description: string | null
          image_url: string | null
          icon: string | null
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          parent_id?: string | null
          name: string
          slug: string
          description?: string | null
          image_url?: string | null
          icon?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          parent_id?: string | null
          name?: string
          slug?: string
          description?: string | null
          image_url?: string | null
          icon?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          seller_id: string
          category_id: string | null
          name: string
          slug: string
          description: string | null
          short_description: string | null
          base_price: number
          compare_at_price: number | null
          cost_price: number | null
          sku: string | null
          barcode: string | null
          weight: number | null
          dimensions: Json | null
          status: 'draft' | 'active' | 'inactive' | 'out_of_stock' | 'deleted'
          is_featured: boolean
          is_digital: boolean
          requires_shipping: boolean
          brand: string | null
          tags: string[] | null
          rating_average: number
          rating_count: number
          view_count: number
          sales_count: number
          created_at: string
          updated_at: string
          published_at: string | null
        }
        Insert: {
          id?: string
          seller_id: string
          category_id?: string | null
          name: string
          slug: string
          description?: string | null
          short_description?: string | null
          base_price: number
          compare_at_price?: number | null
          cost_price?: number | null
          sku?: string | null
          barcode?: string | null
          weight?: number | null
          dimensions?: Json | null
          status?: 'draft' | 'active' | 'inactive' | 'out_of_stock' | 'deleted'
          is_featured?: boolean
          is_digital?: boolean
          requires_shipping?: boolean
          brand?: string | null
          tags?: string[] | null
          rating_average?: number
          rating_count?: number
          view_count?: number
          sales_count?: number
          created_at?: string
          updated_at?: string
          published_at?: string | null
        }
        Update: {
          id?: string
          seller_id?: string
          category_id?: string | null
          name?: string
          slug?: string
          description?: string | null
          short_description?: string | null
          base_price?: number
          compare_at_price?: number | null
          cost_price?: number | null
          sku?: string | null
          barcode?: string | null
          weight?: number | null
          dimensions?: Json | null
          status?: 'draft' | 'active' | 'inactive' | 'out_of_stock' | 'deleted'
          is_featured?: boolean
          is_digital?: boolean
          requires_shipping?: boolean
          brand?: string | null
          tags?: string[] | null
          rating_average?: number
          rating_count?: number
          view_count?: number
          sales_count?: number
          created_at?: string
          updated_at?: string
          published_at?: string | null
        }
      }
      product_images: {
        Row: {
          id: string
          product_id: string
          variant_id: string | null
          url: string
          alt_text: string | null
          position: number
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          variant_id?: string | null
          url: string
          alt_text?: string | null
          position?: number
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          variant_id?: string | null
          url?: string
          alt_text?: string | null
          position?: number
          is_primary?: boolean
          created_at?: string
        }
      }
      product_variants: {
        Row: {
          id: string
          product_id: string
          sku: string | null
          barcode: string | null
          price: number
          compare_at_price: number | null
          cost_price: number | null
          weight: number | null
          option_values: Json
          position: number
          is_default: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          sku?: string | null
          barcode?: string | null
          price: number
          compare_at_price?: number | null
          cost_price?: number | null
          weight?: number | null
          option_values?: Json
          position?: number
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          sku?: string | null
          barcode?: string | null
          price?: number
          compare_at_price?: number | null
          cost_price?: number | null
          weight?: number | null
          option_values?: Json
          position?: number
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      inventory: {
        Row: {
          id: string
          variant_id: string
          quantity: number
          reserved_quantity: number
          low_stock_threshold: number
          track_inventory: boolean
          allow_backorder: boolean
          updated_at: string
        }
        Insert: {
          id?: string
          variant_id: string
          quantity?: number
          reserved_quantity?: number
          low_stock_threshold?: number
          track_inventory?: boolean
          allow_backorder?: boolean
          updated_at?: string
        }
        Update: {
          id?: string
          variant_id?: string
          quantity?: number
          reserved_quantity?: number
          low_stock_threshold?: number
          track_inventory?: boolean
          allow_backorder?: boolean
          updated_at?: string
        }
      }
      cart_items: {
        Row: {
          id: string
          user_id: string
          variant_id: string
          quantity: number
          saved_for_later: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          variant_id: string
          quantity?: number
          saved_for_later?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          variant_id?: string
          quantity?: number
          saved_for_later?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          order_number: string
          user_id: string
          status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
          subtotal: number
          shipping_total: number
          tax_total: number
          discount_total: number
          grand_total: number
          currency: string
          shipping_address: Json
          billing_address: Json
          shipping_method: string | null
          shipping_carrier: string | null
          tracking_number: string | null
          estimated_delivery_date: string | null
          payment_status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
          payment_method: string | null
          stripe_session_id: string | null
          stripe_payment_intent_id: string | null
          notes: string | null
          internal_notes: string | null
          confirmed_at: string | null
          shipped_at: string | null
          delivered_at: string | null
          cancelled_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number?: string
          user_id: string
          status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
          subtotal: number
          shipping_total?: number
          tax_total?: number
          discount_total?: number
          grand_total: number
          currency?: string
          shipping_address: Json
          billing_address: Json
          shipping_method?: string | null
          shipping_carrier?: string | null
          tracking_number?: string | null
          estimated_delivery_date?: string | null
          payment_status?: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
          payment_method?: string | null
          stripe_session_id?: string | null
          stripe_payment_intent_id?: string | null
          notes?: string | null
          internal_notes?: string | null
          confirmed_at?: string | null
          shipped_at?: string | null
          delivered_at?: string | null
          cancelled_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          user_id?: string
          status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
          subtotal?: number
          shipping_total?: number
          tax_total?: number
          discount_total?: number
          grand_total?: number
          currency?: string
          shipping_address?: Json
          billing_address?: Json
          shipping_method?: string | null
          shipping_carrier?: string | null
          tracking_number?: string | null
          estimated_delivery_date?: string | null
          payment_status?: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
          payment_method?: string | null
          stripe_session_id?: string | null
          stripe_payment_intent_id?: string | null
          notes?: string | null
          internal_notes?: string | null
          confirmed_at?: string | null
          shipped_at?: string | null
          delivered_at?: string | null
          cancelled_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          seller_id: string
          product_id: string
          variant_id: string
          product_name: string
          variant_options: Json | null
          sku: string | null
          unit_price: number
          quantity: number
          subtotal: number
          tax_amount: number
          discount_amount: number
          total: number
          commission_rate: number
          commission_amount: number
          seller_amount: number
          status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          seller_id: string
          product_id: string
          variant_id: string
          product_name: string
          variant_options?: Json | null
          sku?: string | null
          unit_price: number
          quantity: number
          subtotal: number
          tax_amount?: number
          discount_amount?: number
          total: number
          commission_rate: number
          commission_amount: number
          seller_amount: number
          status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          seller_id?: string
          product_id?: string
          variant_id?: string
          product_name?: string
          variant_options?: Json | null
          sku?: string | null
          unit_price?: number
          quantity?: number
          subtotal?: number
          tax_amount?: number
          discount_amount?: number
          total?: number
          commission_rate?: number
          commission_amount?: number
          seller_amount?: number
          status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
          created_at?: string
          updated_at?: string
        }
      }
      product_reviews: {
        Row: {
          id: string
          product_id: string
          user_id: string
          order_item_id: string | null
          rating: number
          title: string | null
          content: string | null
          pros: string[] | null
          cons: string[] | null
          is_verified_purchase: boolean
          is_approved: boolean
          helpful_votes: number
          unhelpful_votes: number
          seller_response: string | null
          seller_responded_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          user_id: string
          order_item_id?: string | null
          rating: number
          title?: string | null
          content?: string | null
          pros?: string[] | null
          cons?: string[] | null
          is_verified_purchase?: boolean
          is_approved?: boolean
          helpful_votes?: number
          unhelpful_votes?: number
          seller_response?: string | null
          seller_responded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          user_id?: string
          order_item_id?: string | null
          rating?: number
          title?: string | null
          content?: string | null
          pros?: string[] | null
          cons?: string[] | null
          is_verified_purchase?: boolean
          is_approved?: boolean
          helpful_votes?: number
          unhelpful_votes?: number
          seller_response?: string | null
          seller_responded_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      wishlists: {
        Row: {
          id: string
          user_id: string
          name: string
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name?: string
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      wishlist_items: {
        Row: {
          id: string
          wishlist_id: string
          product_id: string
          variant_id: string | null
          notes: string | null
          priority: number
          created_at: string
        }
        Insert: {
          id?: string
          wishlist_id: string
          product_id: string
          variant_id?: string | null
          notes?: string | null
          priority?: number
          created_at?: string
        }
        Update: {
          id?: string
          wishlist_id?: string
          product_id?: string
          variant_id?: string | null
          notes?: string | null
          priority?: number
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          message: string
          data: Json | null
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          message: string
          data?: Json | null
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          message?: string
          data?: Json | null
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
      }
      hero_banners: {
        Row: {
          id: string
          title: string
          subtitle: string | null
          button_text: string | null
          button_link: string | null
          image_url: string
          background_color: string
          position: number
          is_active: boolean
          start_date: string | null
          end_date: string | null
          click_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          subtitle?: string | null
          button_text?: string | null
          button_link?: string | null
          image_url: string
          background_color?: string
          position?: number
          is_active?: boolean
          start_date?: string | null
          end_date?: string | null
          click_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          subtitle?: string | null
          button_text?: string | null
          button_link?: string | null
          image_url?: string
          background_color?: string
          position?: number
          is_active?: boolean
          start_date?: string | null
          end_date?: string | null
          click_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      featured_categories: {
        Row: {
          id: string
          category_id: string
          custom_title: string | null
          custom_description: string | null
          custom_image_url: string | null
          position: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          category_id: string
          custom_title?: string | null
          custom_description?: string | null
          custom_image_url?: string | null
          position?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          custom_title?: string | null
          custom_description?: string | null
          custom_image_url?: string | null
          position?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          order_id: string
          user_id: string
          stripe_payment_intent_id: string
          stripe_charge_id: string | null
          amount: number
          currency: string
          status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
          payment_method: string | null
          card_brand: string | null
          card_last_four: string | null
          failure_reason: string | null
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          user_id: string
          stripe_payment_intent_id: string
          stripe_charge_id?: string | null
          amount: number
          currency?: string
          status?: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
          payment_method?: string | null
          card_brand?: string | null
          card_last_four?: string | null
          failure_reason?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          user_id?: string
          stripe_payment_intent_id?: string
          stripe_charge_id?: string | null
          amount?: number
          currency?: string
          status?: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
          payment_method?: string | null
          card_brand?: string | null
          card_last_four?: string | null
          failure_reason?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      seller_payouts: {
        Row: {
          id: string
          seller_id: string
          stripe_transfer_id: string
          amount: number
          currency: string
          status: string
          period_start: string | null
          period_end: string | null
          order_item_ids: string[] | null
          notes: string | null
          processed_at: string | null
          failure_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          seller_id: string
          stripe_transfer_id: string
          amount: number
          currency?: string
          status?: string
          period_start?: string | null
          period_end?: string | null
          order_item_ids?: string[] | null
          notes?: string | null
          processed_at?: string | null
          failure_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          seller_id?: string
          stripe_transfer_id?: string
          amount?: number
          currency?: string
          status?: string
          period_start?: string | null
          period_end?: string | null
          order_item_ids?: string[] | null
          notes?: string | null
          processed_at?: string | null
          failure_reason?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      product_views: {
        Row: {
          id: string
          product_id: string
          user_id: string | null
          session_id: string | null
          ip_address: string | null
          user_agent: string | null
          referrer: string | null
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          user_id?: string | null
          session_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          referrer?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          user_id?: string | null
          session_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          referrer?: string | null
          created_at?: string
        }
      }
      review_votes: {
        Row: {
          id: string
          review_id: string
          user_id: string
          is_helpful: boolean
          created_at: string
        }
        Insert: {
          id?: string
          review_id: string
          user_id: string
          is_helpful: boolean
          created_at?: string
        }
        Update: {
          id?: string
          review_id?: string
          user_id?: string
          is_helpful?: boolean
          created_at?: string
        }
      }
      admin_audit_log: {
        Row: {
          id: string
          admin_id: string
          action: string
          target_user_id: string | null
          target_entity_type: string | null
          target_entity_id: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          admin_id: string
          action: string
          target_user_id?: string | null
          target_entity_type?: string | null
          target_entity_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          admin_id?: string
          action?: string
          target_user_id?: string | null
          target_entity_type?: string | null
          target_entity_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
      }
      platform_settings: {
        Row: {
          id: string
          key: string
          value: Json
          updated_by: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          key: string
          value: Json
          updated_by?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          key?: string
          value?: Json
          updated_by?: string | null
          updated_at?: string
        }
      }
      user_addresses: {
        Row: {
          id: string
          user_id: string
          label: string | null
          recipient_name: string
          phone: string | null
          street_address: string
          street_address_2: string | null
          city: string
          state: string
          postal_code: string
          country: string
          is_default_shipping: boolean
          is_default_billing: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          label?: string | null
          recipient_name: string
          phone?: string | null
          street_address: string
          street_address_2?: string | null
          city: string
          state: string
          postal_code: string
          country?: string
          is_default_shipping?: boolean
          is_default_billing?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          label?: string | null
          recipient_name?: string
          phone?: string | null
          street_address?: string
          street_address_2?: string | null
          city?: string
          state?: string
          postal_code?: string
          country?: string
          is_default_shipping?: boolean
          is_default_billing?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'customer' | 'seller' | 'admin'
      seller_status: 'pending' | 'approved' | 'suspended' | 'rejected'
      order_status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'refunded' | 'returned'
      payment_status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded'
      product_status: 'draft' | 'active' | 'inactive' | 'out_of_stock' | 'deleted'
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
